name: client

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  docker-client:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: rstropek/starshipclient:latest
          file: Client.Dockerfile
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - 
        name: Deploy Stage
        uses: fjogeleit/http-request-action@master
        with:
          url: ${{ secrets.CLIENT_AZURE_WEBHOOK }}
          method: 'POST'
